### ISSUE TITLE
[SPIN] Setting PWM duty cycle - Big issue

### ISSUE THREAD

**Issue by jalinei** [owntech-foundation/examples#23]
No longer have serial monitor. 
Cannot reflash without recovery mode

**Comment by Ayoub-Farah** [comment]
The examples needs to be updated since the recent [merge request](https://github.com/owntech-foundation/Core/pull/57) .

We need to replace `spin.pwm.setFrequency` by : 

```cpp
    spin.pwm.initFrequency(200000); // Set frequency of pwm
 ```

`spin.pwm.setFrequency`  is called after the timing unit initialization to update frequency.
`spin.pwm.initFrequency` is called before the timing unit to choose the frequency when starting PWM.
